---

- name: install personal cask applications
  homebrew_cask:
    name: "{{item}}"
    state: present
    install_options: --appdir=/Applications
  with_items:
  - coconutbattery
#  - sleepyhead # replaced by ...
  - veracrypt

- name: install personal brew applications
  homebrew: name={{item}} state=latest
  with_items:
  - lame
  - ffmpeg
  - youtube-dl
  - speedtest-cli
  - karabiner-elements
