---
- name: "[Golang] Install golang"
  homebrew: name={{item}} state=latest
  with_items:
    - go
    - gobject-introspection
    - glide

- name: "[Golang] Make go src directory"
  file: path={{ home_dir }}/src/go state=directory

- name: "[Golang] Set GOPATH"
  lineinfile: dest={{ home_dir }}/.bash_profile
              line="export GOPATH={{ home_dir}}/src/go"

- name: "[Golang] Set GOBIN"
  lineinfile: dest={{ home_dir }}/.bash_profile
              line="export GOBIN=$GOPATH/bin"

- name: "[Golang] Put Go binaries on path"
  lineinfile: dest={{ home_dir }}/.bash_profile
              line="export PATH=$PATH:$GOPATH/bin"
