---
- hosts: localhost
  connection: local

  vars:
    # Set these in secrets file:
    # github_auth_token
    # apple_id_password

    - superlimic_config_repo: https://github.com/joffotron/superlumic-config.git
    - user_name: joff
    - computername: ams-mac-020
    - home_dir: "/Users/{{ user_name }}/"
    - user_email: joff@joff.codes
    - github_user_name: joffotron
    - git_user_name: Joseph Miller
    - git_user_email: "{{ user_email }}"
    - git_signing_key: FAEF0DE3
    - apple_id_email: joff@googlehax.com
    - src_dir: "{{ home_dir }}/src/"
    - settings_export_dir: "{{ home_dir }}/tmp/SettingsExports"
    - nextcloud_gnupg_dir: "{{ home_dir }}/Nextcloud/TheCrypt/GPG/gnupg"

  vars_files:
    - vars/osx_defaults.yml
    - vars/nodejs.yml
    - vars/{{ user_name }}-secrets.yml

  roles:
    - { role: zsh, tags: zsh }
    - { role: apple-silicon, tags: applechip }
    - { role: profile-all, tags: base }
    - { role: profile-developer, tags: base-dev }
    - { role: ruby, tags: ruby }
    - { role: nodejs, tags: nodejs }
    - { role: mobile-dev, tags: mobile-dev }
#    - { role: golang, tags: golang }
#    - { role: elixir, tags: elixir }
#    - { role: python, tags: python }
#    - { role: roderik.superlumic-postgresql, tags: postgres }

  tasks:
    - name: install personal cask applications
      homebrew_cask:
        name: "{{item}}"
        state: present
        install_options:
        - cask
        - appdir=/Applications
        - no-quarantine
      with_items:
        - 1password
        - 1password-cli
        - alfred
        - android-file-transfer
        - balenaetcher
        - bettertouchtool
        - controlplane
        - choosy
        - discord
        - disk-inventory-x
        - firefox
        - fluent-reader
        - dropbox
        - flux
        - jordanbaird-ice
        - istat-menus
        - joplin
        - nextcloud
        - signal
        - skitch
        - sonos
        - shortcat
        - spotify
        - transmit
        - whatsapp
        - yt-music
        - yubico-yubikey-manager
        #- viscosity

    - name: Create local bin dir
      file: path="{{ home_dir }}/bin" state=directory

    - name: Copy local 'binaries'
      copy: src=files/{{ user_name }}/bin/
            dest="{{ home_dir }}/bin/"

    - name: install personal brew applications
      homebrew: name={{item}} state=latest
      with_items:
        - certbot
        - ipcalc
        - fzf
        - jq
        - mas
        - moreutils
        - packer
        - pidof
        - s3cmd
        - ykpers
        - ykman
        - zsh
        - speedtest-cli
        - yubikey-personalization
        - yubico-piv-tool

    - name: install fzf
      command: /opt/homebrew/opt/fzf/install
      when: "'FZF_DEFAULT_COMMAND' not in ansible_env"

    # - name: "[App Store] Sign out of the Mac App Store"
    #   command: mas signout

    # - name: "[App Store] Sign in to the Mac App Store"
    #   command: mas signin {{ apple_id_email }} "{{ apple_id_password }}"

    - name: "[App Store] See which apps are already installed"
      command: bash -c "mas list | cut -f 1 -d ' '"
      register: mas_list

    - name: "[App Store] Install Mac App Store applications"
      command: mas install {{ item.id }}
      when: item.id not in mas_list.stdout_lines
      with_items:
        - { id: "409183694", name: "Keynote" }
        - { id: "409201541", name: "Pages" }
        - { id: "409203825", name: "Numbers" }
        - { id: "419330170", name: "Moom" }
        - { id: "495152161", name: "Wizard" }
        - { id: "585829637", name: "Todoist" }
        - { id: "587512244", name: "Kaleidoscope" }
        - { id: "824171161", name: "Affinity Designer" }
        - { id: "824183456", name: "Affinity Photo" }
        - { id: "964860276", name: "Folder Designer" }
        - { id: "975937182", name: "Fantastical" }
        - { id: "1357379892", name: "Menu Bar Controller for Sonos" }
        - { id: "1507782672", name: "Pixea" }
#        - { id: "715768417", name: "Microsoft Remote Desktop" }
#        - { id: "408981434", name: "iMovie" }
#        - { id: "571213070", name: "DaVinci Resolve" }
#        - { id: "682658836", name: "GarageBand" }
#        - { id: "784801555", name: "Microsoft OneNote" }
#        - { id: "957734279", name: "Toggl Desktop" }

    - name: create .ssh directory
      file:
        path: "{{ home_dir }}/.ssh/"
        state: directory
        mode: 0700

    - name: personal ssh config
      copy:
        src: files/ssh_config
        dest: "{{ home_dir }}/.ssh/ssh_config"

    - name: Create SettingsExports dir
      file: path={{ settings_export_dir }} state=directory

    - name: Copy Settings Files
      copy: src="{{ user_name }}/{{ item }}" dest="{{ settings_export_dir }}/{{ item }}"
      with_items:
        - com.apple.symbolichotkeys.plist
        - pbs.plist
        - dot-GlobalPreferences.plist
        - iStatMenusSettings.ismp
        - BetterTouchTool.settings.bttpreset
        - com.manytricks.Moom.plist

#    - name: killall cfprefsd so we can copy prefs
#      command: killall cfprefsd

    #    - name: OSX Keyboard shortcuts
    #command: defaults import com.apple.symbolichotkeys {{ settings_export_dir }}/osx-keybindings.plist
    #tags: osxshortcuts

    - name: Kill Moom
      command: kill `pidof Moom`
      ignore_errors: true

    - name: Copy moom config
      copy: src={{ user_name }}/com.manytricks.Moom.plist dest="{{ home_dir }}/Library/Preferences/com.manytricks.Moom.plist"
#
    - name: Start Moom again
      command: open /Applications/Moom.app

    - name: Check stat of .gnupg dir
      stat: path={{ home_dir }}/.gnupg
      register: gnupg_dir_stat

    - name: Remove .gnupg dir if it exists
      file: path={{ home_dir }}/.gnupg
            state=absent
      when: gnupg_dir_stat.stat.exists == True and gnupg_dir_stat.stat.islnk == False

    - name: Link GPG directory from NextCloud
      file: path={{ home_dir }}/.gnupg
            src={{ nextcloud_gnupg_dir }}
            mode=0600
            state=link

    - name: Permissions on gnupg dir
      file: path={{ nextcloud_gnupg_dir }}
            owner={{ user_name }}
            group=staff
            mode=0700

    - name: Download custom fonts
      get_url: url=https://github.com/tonsky/FiraCode/releases/download/1.102/FiraCode_1.102.zip
               dest="{{ home_dir }}/tmp"

    - name: Install fonts
      unarchive: src="{{ home_dir }}/tmp/FiraCode_1.102.zip"
                 dest="{{ home_dir }}/Library/Fonts/"

    - name: Create vim plugin dir
      file: path="{{ home_dir }}/.vim/plugin" state=directory

    - name: Install GPGVim plugin
      get_url: url=https://raw.githubusercontent.com/jamessan/vim-gnupg/master/plugin/gnupg.vim
               dest="{{ home_dir }}/.vim/plugin/gnupg.vim"

    - name: "Ensure ~/Applications dir"
      file: path="{{ home_dir }}/Applications" state=directory
