#coloured less
export LESS="-erX"

alias gs='git status '
alias gu='git up '
alias ga='git add '
alias gb='git branch '
alias gc='git commit'
alias gd='git difftool'
alias gp='git push '
alias prune='git remote prune origin'
alias publish='git publish origin'

alias ll='ls -l '
alias la='ls -a '
alias lla='ls -la '

alias zx='zeus'
alias sc='rails console'
alias be='bundle exec'
alias psp='nice -n 20 ;rake ci:setup:rspec parallel:spec[9]'
alias d='docker'
alias dcom='docker-compose'
alias ls='ls -G'

alias bundlestubs="bundle install --binstubs .bundle/bin"

alias ffs="sudo !!"

alias ne="PATH=$(npm bin):$PATH "

eval "$(rbenv init -)"

if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi

export GOPATH=$HOME/src/go
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:/usr/local/sbin

export EDITOR=vim

. `brew --prefix`/etc/profile.d/z.sh

if [ -f $(brew --prefix)/etc/bash_completion ]; then
        . $(brew --prefix)/etc/bash_completion
fi

complete -C aws_completer aws
