#coloured less
export LESS="-erX"

alias gs='git status '
alias gu='git up '
alias ga='git add '
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias gdt='git difftool'
alias gds='git diff --staged'
alias gp='git push '
alias prune='git remote prune origin'
alias publish='git publish origin'
alias webserver='ruby -run -ehttpd . -p8000'
alias pr-done="git co master && gu && git delete-merged-branches; gu"
alias jsonformat="pbpaste | jq . | pbcopy"
alias jsonunformat="pbpaste | jq . -c | pbcopy"


alias rb='cd $HOME/src/Raisebook/raisebook'
alias bb='cd $HOME/src/Raisebook/bookbuild'
alias lm='cd $HOME/src/Raisebook/lambda'
alias lm='cd $HOME/src/Raisebook/qbot'


alias ll='ls -l '
alias la='ls -a '
alias lla='ls -la '

alias zx='zeus'
alias be='bundle exec'
alias d='docker'
alias ls='ls -G'

alias mixconsole="iex -S mix run --no-start"

alias bundlestubs="bundle install --binstubs .bundle/bin"

alias ffs="sudo !!"

alias fix_docker_clock="docker run --rm --privileged alpine hwclock -s"

alias ne="PATH=$(npm bin):$PATH "

eval "$(rbenv init -)"

if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi

export PATH=$PATH:/usr/local/sbin
export PATH=$PATH:$HOME/Applications/android-sdk-macosx/platform-tools/

export EDITOR=vim

. `brew --prefix`/etc/profile.d/z.sh

if [ -f $(brew --prefix)/etc/bash_completion ]; then
        . $(brew --prefix)/etc/bash_completion
fi

complete -C aws_completer aws
