---

- name: "install node"
  homebrew: name={{item}} state=latest
  with_items:
  - node
  - fnm

- name: "FNM in zshrc"
  lineinfile:
    path: "{{ home_dir }}/.zshrc"
    create: false
    insertbefore: '^# To customise prompt.*'
    line: eval "$(fnm env --use-on-cd)"
