---
- name: "[zsh] Tap homebrew fonts"
  homebrew_tap: tap={{ item }} state=present
  with_items:
  - homebrew/cask-fonts

- name: "[zsh] Install svn"
  homebrew:
    name: svn

- name: "[zsh] Install powerline fonts"
  homebrew_cask: name={{item}} state=present
  with_items:
  - font-anonymice-powerline
  - font-inconsolata-for-powerline
  - font-noto-mono-for-powerline
  - font-consolas-for-powerline
  - font-inconsolata-g-for-powerline
  - font-roboto-mono-for-powerline
  - font-dejavu-sans-mono-for-powerline
  - font-liberation-mono-for-powerline
  - font-source-code-pro-for-powerline
  - font-droid-sans-mono-for-powerline
  - font-menlo-for-powerline
  - font-ubuntu-mono-derivative-powerline
  - font-fira-mono-for-powerline
  - font-meslo-for-powerline
  - font-inconsolata-dz-for-powerline
  - font-monofur-for-powerline

