---
- name: "[Raisebook] Make src directory"
  file: path="{{ raisebook_src }}/" state=directory

- name: "[Raisebook] Checkout repositories"
  git: repo="ssh://git@github.com/{{ item.value.account }}/{{ item.value.repo }}.git"
       dest="{{ raisebook_src }}/{{ item.value.repo }}"
       update=no
  with_dict: "{{ projects }}"

- name: "[Raisebook] Check for subtree remotes"
  command: bash -c "git remote"
           chdir="{{ raisebook_src }}/raisebook"
  register: found_raisebook_remotes

- name: "[Raisebook] Add subtree remote {{ item.name }}"
  command: git remote add {{ item.name }} {{ item.remote }}
           chdir="{{ raisebook_src }}/raisebook"
  when: item.name not in found_raisebook_remotes.stdout_lines
  with_items:
    - { name: 'backend',  remote: 'git@github.com:raisebook/backend.git' }
    - { name: 'proxy',    remote: 'git@github.com:raisebook/proxy.git' }

- name: "[Raisebook] Add project bin dirs to path"
  lineinfile: dest={{ home_dir }}/.bash_profile
              line="export PATH=$PATH:{{ raisebook_src }}/{{ item.key }}/bin"
  with_dict: "{{ projects }}"

- name: "[Raisebook] Add init for subcommands to bash_profile"
  lineinfile: dest={{ home_dir }}/.bash_profile
              line="eval \"$(/Users/joff/src/Raisebook/{{ item.key }}/bin/sub/bin/{{ item.helper }} init -)\""
  with_dict: "{{ projects }}"

- name: "[Raisebook] Install Google Cloud SDK"
  homebrew_cask: name={{item}} state=present
  with_items:
    - google-cloud-sdk

- name: "[Raisebook] Google Cloud install to bash_profile"
  blockinfile:
    path: "{{ home_dir }}/.bash_profile"
    block: |
      source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.bash.inc'
      source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.bash.inc'
