---
- name: "[Raisebook] Make src directory"
  file: path="{{ raisebook_src }}/" state=directory

- name: "[Raisebook] Checkout repositories"
  git: repo="ssh://git@github.com/{{ item.account }}/{{ item.repo }}.git"
       dest="{{ raisebook_src }}/{{ item.repo }}"
       update=no
  with_items:
    - { account: 'raisebook', repo: 'raisebook' }
    - { account: 'raisebook', repo: 'backend' }
    - { account: 'raisebook', repo: 'frontend' }
    - { account: 'raisebook', repo: 'proxy' }
    - { account: 'raisebook', repo: 'deploy' }
    - { account: 'raisebook', repo: 'raisemail' }

- name: "[Raisebook] Check for subtree remotes"
  command: bash -c "git remote"
           chdir="{{ raisebook_src }}/raisebook"
  register: found_raisebook_remotes

- name: "[Raisebook] Add subtree remote {{ item.name }}"
  command: git remote add {{ item.name }} {{ item.remote }}
           chdir="{{ raisebook_src }}/raisebook"
  when: item.name not in found_raisebook_remotes.stdout_lines
  with_items:
    - { name: 'backend',  remote: 'git@github.com:raisebook/backend.git' }
    - { name: 'proxy',    remote: 'git@github.com:raisebook/proxy.git' }

- name: "[Raisebook] Add project bin dirs to path"
  lineinfile: dest={{ home_dir }}/.bash_profile
              line="export PATH=$PATH:{{ raisebook_src }}/{{ item }}/bin"
  with_items:
    - raisebook
    - raisemail
