---

- name: "[Developer] tap caskroom/versions"
  homebrew_tap: tap=caskroom/versions state=present

- name: "[Developer] tap homebrew/dupes"
  homebrew_tap: tap=homebrew/dupes state=present

- name: "[Developer] tap codeclimate/formulae"
  homebrew_tap: tap=codeclimate/formulae state=present

- name: "[Developer] Install developer brew applications"
  homebrew: name={{item}} state=latest
  with_items:
    - awscli
    - direnv
    - htop
    - httpie
    - pwgen
    - rsync
    - shellcheck
    - watch
    - wget
    - yarn

- name: "[Developer] Homebrew developer taps"
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - Caskroom/cask
    - wallix/awless

- name: "[Developer] Install developer cask applications"
  homebrew_cask: name={{item}} state=present
  with_items:
    - awless
    - aws-vault
    - dash
    - datagrip
    - drawio
    - google-cloud-sdk
    - gpgtools
    - hosts
    - imageoptim
    - intellij-idea
    - iterm2
    - java
    - ngrok
    - wireshark

- name: Install Python pip packages
  pip: state=present name="{{ item }}"
  with_items:
  - awslogs
  - csvkit
  - yamllint

- name: "[Developer] Copy dotfiles"
  copy: src=files/{{ user_name }}/{{ item }} dest={{ home_dir }}/.{{ item }}
  with_items:
    - bash_profile
    - bashrc
    - npmrc
    - vimrc

- name: Write out gitconfig
  template: src=gitconfig.j2 dest={{ home_dir }}/.gitconfig

- name: "[Developer] Install completions"
  homebrew: name={{item}} state=latest
  with_items:
    - bundler-completion
    - cap-completion
    - docker-compose-completion
    - gem-completion
    - mix-completion
    - pip-completion
    - rails-completion
    - rake-completion
    - ruby-completion
    - yarn-completion

- name: "[Developer] Ensure ~/Applications dir"
  file: path="{{ home_dir }}/Applications" state=directory

# - name: "[Developer] Install 'awsp' aws node.js package globally."
#   npm:
#     name: awsp
#     global: yes

# - name: "[Developer] setup bash_profile for aws stuff"
#   blockinfile:
#     dest: "{{home_dir}}/.bash_profile"
#     block: |
#       complete -C aws_completer aws
#       alias aws="aws-wrapper"
#       alias awsp="source _awsp"

- name: "[Developer] install aws-profile"
  git: repo=https://github.com/jaymecd/aws-profile.git
       dest="{{ home_dir }}/Applications/aws-profile"
       update=no

- name: "[Developer] link aws-profile binaries"
  file: src="{{home_dir}}/Applications/aws-profile/{{item}}"
        dest="/usr/local/bin/{{ item }}"
        state=link
  with_items:
    - aws-profile
    - aws-wrapper

- name: "[Developer] setup bash_profile for aws-profile"
  blockinfile:
    dest: "{{home_dir}}/.bash_profile"
    block: |
      complete -C aws_completer aws
      alias aws-profile="source aws-profile"
      alias aws="aws-wrapper"
      aws-profile default

- name: "[Developer] Activate direnv"
  lineinfile:
    dest: "{{home_dir}}/.bash_profile"
    line: eval "$(direnv hook bash)"
