---

- name: "[Developer] tap caskroom/versions"
  homebrew_tap: tap=caskroom/versions state=present

- name: "[Developer] tap homebrew/dupes"
  homebrew_tap: tap=homebrew/dupes state=present

- name: "[Developer] Tap homebrew/completions"
  homebrew_tap: tap=homebrew/completions state=present

- name: "[Developer] tap codeclimate/formulae"
  homebrew_tap: tap=codeclimate/formulae state=present

- name: "[Developer] Install developer brew applications"
  homebrew: name={{item}} state=latest
  with_items:
    - wget
    - pwgen
    - htop
    - httpie
    - watch
    - rsync
    - awscli
    - pinentry
    - lastpass-cli
    - shellcheck
    - codeclimate

- name: "[Developer] Install developer cask applications"
  homebrew_cask: name={{item}} state=present
  with_items:
    - java
    - gpgtools
    - dash
    - iterm2
    - ngrok

- name: "[Developer] Copy dotfiles"
  copy: src=files/{{ user_name }}/{{ item }} dest={{ home_dir }}/.{{ item }}
  with_items:
    - bashrc
    - bash_profile
    - npmrc
    - vimrc

- name: Write out gitconfig
  template: src=gitconfig.j2 dest={{ home_dir }}/.gitconfig

- name: "[Developer] Install completions"
  homebrew: name={{item}} state=latest
  with_items:
    - docker-compose-completion
    - gem-completion
    - mix-completion
    - pip-completion
    - rails-completion
    - rake-completion
    - ruby-completion
    - cap-completion
    - bundler-completion

- name: "[Developer] Ensure ~/Applications dir"
  file: path="{{ home_dir }}/Applications" state=directory

- name: "[Developer] install aws-profile"
  git: repo=https://github.com/jaymecd/aws-profile.git
       dest="{{ home_dir }}/Applications/aws-profile"
       update=no

- name: "[Developer] link aws-profile binaries"
  file: src="{{home_dir}}/Applications/aws-profile/{{item}}"
        dest="/usr/local/bin/{{ item }}
        state=link
  with_items:
    - aws-profile
    - aws-wrapper

- name: "[Developer] setup bash_profile for aws-profile"
  blockinfile:
    dest: "{{home_dir}}/.bash_profile"
    block: |
      complete -C aws_completer aws
      alias aws-profile="source aws-profile"
      alias aws="aws-wrapper"

