---
- name: "[Developer] Install developer brew applications"
  homebrew: name={{item}} state=latest
  with_items:
    - awscli
    - bat
    - direnv
    - htop
    - httpie
    - java
    - pwgen
    - rsync
    - shellcheck
    - watch
    - wget
    - yarn

- name: "[Developer] Install developer cask applications"
  homebrew_cask: name={{item}} state=present
  with_items:
    - aws-vault
    - boop
    - dash
    - datagrip
    - drawio
    - monodraw
    - gpg-suite
    - imageoptim
    - intellij-idea
    - iterm2
    - insomnia
    - ksdiff
    - ngrok
    - pop
    - postman
    - wireshark

# TODO: Install using `go get` for MacOS ARM
#- name: "[Developer] Fetch awless installer content"
#  uri:
#    url: https://raw.githubusercontent.com/wallix/awless/master/getawless.sh
#    return_content: yes
#  register: awless_installer
#
#- name: "[Developer] Run awless installer"
#  shell:
#    chdir: "{{ home_dir }}"
#    cmd: bash -
#    warn: no
#    stdin: "{{ awless_installer.content }}"
#
#- name: "[Developer] Put awless in /usr/local/bin"
#  become: yes
#  command: mv "{{ home_dir }}/awless" /usr/local/bin/

- name: "[Developer] Download Hosts App"
  get_url:
    url: https://www.dirk-froehling.de/resources/Software/Hosts-App-1.4.5.zip
    dest: "{{ home_dir }}/Downloads"

- name: "[Developer] Unpack Hosts App"
  become: yes
  unarchive:
    remote_src: yes
    src: "{{ home_dir }}/Downloads/Hosts-App-1.4.5.zip"
    dest: "/Applications"

- name: Install Python pip packages
  pip: state=present executable=pip3 name="{{ item }}"
  with_items:
  - awslogs
  - csvkit
  - yamllint

- name: "[Developer] Copy dotfiles"
  copy: src=files/{{ user_name }}/{{ item }} dest={{ home_dir }}/.{{ item }}
  with_items:
    - bash_profile
    - bashrc
    - npmrc
    - vimrc

- name: Write out gitconfig
  template: src=gitconfig.j2 dest={{ home_dir }}/.gitconfig

- name: "[Developer] Install completions"
  homebrew: name={{item}} state=latest
  with_items:
    - bundler-completion
    - cap-completion
    - gem-completion
    - mix-completion
    - pip-completion
    - rails-completion
    - rake-completion
    - ruby-completion
    - yarn-completion

- name: "[Developer] Ensure ~/Applications dir"
  file: path="{{ home_dir }}/Applications" state=directory

- name: "[Developer] Activate direnv"
  lineinfile:
    dest: "{{home_dir}}/.bash_profile"
    line: eval "$(direnv hook bash)"

- name: "[Developer] Ensure .aws directory"
  file: path="{{ home_dir }}/.aws" state=directory

- name: "[Developer] AWS Base config file"
  blockinfile:
    dest: "{{ home_dir }}/.aws/config"
    create: yes
    block: |
      [default]
      output=json
      region=ap-southeast-2

- name: "[Developer] Ensure home bin directory"
  file:
    path: "{{ home_dir }}/bin"
    state: directory

- name: "[Developer] Install aws-kms"
  get_url:
    url: https://github.com/joffotron/aws-kms/releases/download/v0.1.0/aws-kms-linux-amd64
    dest: "{{ home_dir }}/bin/aws-kms"
    mode: '0755'

