---
- name: "[Developer] Homebrew developer taps"
  homebrew_tap: tap={{ item }} state=present
  with_items:
  - wallix/awless

- name: "[Developer] Install developer brew applications"
  homebrew: name={{item}} state=latest
  with_items:
    - awscli
    - awless
    - bat
    - direnv
    - htop
    - httpie
    - pwgen
    - rsync
    - shellcheck
    - watch
    - wget
    - yarn

- name: "[Developer] Install developer cask applications"
  homebrew_cask: name={{item}} state=present
  with_items:
    - aws-vault
    - boop
    - dash
    - datagrip
    - drawio
    - monodraw
    - gpg-suite
    - gpgtools
    - hosts
    - imageoptim
    - intellij-idea
    - iterm2
    - insomnia
    - java
    - ksdiff
    - ngrok
    - pop
    - postman
    - wireshark

- name: Install Python pip packages
  pip: state=present executable=pip3 name="{{ item }}"
  with_items:
  - awslogs
  - csvkit
  - yamllint

- name: "[Developer] Copy dotfiles"
  copy: src=files/{{ user_name }}/{{ item }} dest={{ home_dir }}/.{{ item }}
  with_items:
    - bash_profile
    - bashrc
    - npmrc
    - vimrc

- name: Write out gitconfig
  template: src=gitconfig.j2 dest={{ home_dir }}/.gitconfig

- name: "[Developer] Install completions"
  homebrew: name={{item}} state=latest
  with_items:
    - bundler-completion
    - cap-completion
    - docker-compose-completion
    - gem-completion
    - mix-completion
    - pip-completion
    - rails-completion
    - rake-completion
    - ruby-completion
    - yarn-completion

- name: "[Developer] Ensure ~/Applications dir"
  file: path="{{ home_dir }}/Applications" state=directory

- name: "[Developer] Activate direnv"
  lineinfile:
    dest: "{{home_dir}}/.bash_profile"
    line: eval "$(direnv hook bash)"

- name: "[Developer] Ensure .aws directory"
  file: path="{{ home_dir }}/.aws" state=directory

- name: "[Developer] AWS Base config file"
  blockinfile:
    dest: "{{ home_dir }}/.aws/config"
    create: yes
    block: |
      [default]
      output=json
      region=ap-southeast-2


- name: Install aws-kms
  get_url:
    url: https://github.com/joffotron/aws-kms/releases/download/v0.1.0/aws-kms-linux-amd64
    dest: "{{ home_dir }}/bin/aws-kms"
    mode: '0755'

